name: test
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check the name
        run: echo "This is the build job"
      - name: checout the code
        uses: actions/checkout@v3
      - name: check directory structure
        run: |
            echo "The directory structure is as follows:"
            ls -R
            pwd
            mkdir /target
      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: java11-examples
          path: target
